source = ~/.config/hypr/colors.conf

general {
    hide_cursor = true
    grace = 3
}

background {
    monitor =
    color = $bg_hard
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    brightness = 0.7
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = $bg2
    inner_color = $bg0
    font_color = $fg
    fade_on_empty = true
    placeholder_text = <i>haslo...</i>
    check_color = $orange
    fail_color = $red
    fail_text = <i>$FAIL</i>
    halign = center
    valign = center
    position = 0, -50
}

label {
    monitor =
    text = $TIME
    color = $fg_bright
    font_size = 72
    font_family = Inter
    halign = center
    valign = center
    position = 0, 120
}

label {
    monitor =
    text = cmd[update:3600000] date +"%A, %d %B"
    color = $fg_dim
    font_size = 20
    font_family = Inter
    halign = center
    valign = center
    position = 0, 50
}
